version: '3.5'

services:
  nginx:
    image: nginx:1.21.5
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - ./src:/var/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/:/var/log/nginx/
